[build]
  command = "npm ci && npm run docs:build"
  publish = "src/.vuepress/dist"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"
    Access-Control-Allow-Origin = "*"

[context.production]
  environment = { NODE_VERSION = "18" }

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"