[build]
  command = "npm ci && npm run docs:build"
  publish = "src/.vuepress/dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"
    Access-Control-Allow-Origin = "*"

# Ensure no authentication is required
[context.production]
  environment = { NODE_VERSION = "18" }

# Optional: Set cache headers
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"